# Generated by Django 5.2 on 2025-04-29 15:54

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image1', models.ImageField(upload_to=myapp.models.get_file_path)),
                ('image2', models.ImageField(upload_to=myapp.models.get_file_path)),
                ('image3', models.ImageField(upload_to=myapp.models.get_file_path)),
                ('short_description', models.TextField(max_length=500)),
                ('long_description', models.TextField(max_length=500)),
                ('main_prod', models.BooleanField(default=False, help_text='1 for main product and 0 for modules')),
                ('trending', models.BooleanField(default=False, help_text='1 to show in the home page')),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=150, null=True)),
                ('resolution', models.CharField(blank=True, max_length=150, null=True)),
                ('processor', models.CharField(blank=True, max_length=150, null=True)),
                ('ram', models.CharField(blank=True, max_length=150, null=True)),
                ('storage', models.CharField(blank=True, max_length=150, null=True)),
                ('os', models.CharField(blank=True, max_length=150, null=True)),
                ('battery', models.CharField(blank=True, max_length=150, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
