# Generated by Django 5.2 on 2025-05-01 13:47

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_app_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_app_file),
        ),
    ]
