# Generated by Django 5.2 on 2025-05-01 17:22

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_device_linkeddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=myapp.models.generate_device_id, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(default='zero', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='paperspace', max_length=100),
        ),
    ]
